#!/bin/bash
set -e

# pgEdge Natural Language Agent Initialization Script
# This script initializes users and tokens from environment variables
#
# Database Configuration:
#   Single database (backward compatible):
#     PGEDGE_DB_HOST, PGEDGE_DB_PORT, PGEDGE_DB_NAME, PGEDGE_DB_USER,
#     PGEDGE_DB_PASSWORD, PGEDGE_DB_SSLMODE
#
#   Multiple databases (use numbered variables):
#     PGEDGE_DB_1_NAME, PGEDGE_DB_1_HOST, PGEDGE_DB_1_PORT, PGEDGE_DB_1_DATABASE,
#     PGEDGE_DB_1_USER, PGEDGE_DB_1_PASSWORD, PGEDGE_DB_1_SSLMODE, PGEDGE_DB_1_ALLOW_WRITES
#     PGEDGE_DB_2_NAME, PGEDGE_DB_2_HOST, ...
#     (supports up to 99 databases)

echo "Starting pgEdge Natural Language Agent..."

# Build command line arguments
ARGS=""

# Add HTTP mode and address
ARGS="$ARGS -http -addr :8080"

# Function to check if multiple databases are configured
has_multiple_databases() {
    # Check if any PGEDGE_DB_N_* variables exist (N = 1-99)
    for n in $(seq 1 99); do
        eval "name_var=\$PGEDGE_DB_${n}_NAME"
        eval "host_var=\$PGEDGE_DB_${n}_HOST"
        if [ -n "$name_var" ] || [ -n "$host_var" ]; then
            return 0  # true - multiple databases configured
        fi
    done
    return 1  # false - no multiple databases
}

# Function to generate YAML config for multiple databases
generate_multi_db_config() {
    local config_file="$1"
    echo "Generating multi-database config file: $config_file"

    cat > "$config_file" << 'YAML_HEADER'
# Auto-generated configuration for multiple databases
# Generated by init-server.sh from environment variables

http:
    enabled: true
    address: ":8080"
    auth:
        enabled: true
YAML_HEADER

    # Add LLM database switching if enabled via environment variable
    case "$PGEDGE_LLM_DB_SWITCHING" in
        true|TRUE|1|yes|YES)
            cat >> "$config_file" << 'YAML_BUILTINS'

builtins:
    tools:
        llm_connection_selection: true
YAML_BUILTINS
            echo "LLM database switching enabled (PGEDGE_LLM_DB_SWITCHING=$PGEDGE_LLM_DB_SWITCHING)"
            ;;
        *)
            echo "LLM database switching disabled (set PGEDGE_LLM_DB_SWITCHING=true to enable)"
            ;;
    esac

    cat >> "$config_file" << 'YAML_DATABASES'

databases:
YAML_DATABASES

    DB_COUNT=0

    # First, add the default database if configured (backward compatibility)
    if [ -n "$PGEDGE_DB_HOST" ] || [ -n "$PGEDGE_DB_NAME" ]; then
        DB_COUNT=$((DB_COUNT + 1))
        local db_name="${PGEDGE_DB_NAME:-default}"
        cat >> "$config_file" << YAML_DB
    - name: "${db_name}"
      host: "${PGEDGE_DB_HOST:-localhost}"
      port: ${PGEDGE_DB_PORT:-5432}
      database: "${PGEDGE_DB_NAME:-postgres}"
      user: "${PGEDGE_DB_USER:-postgres}"
      password: "${PGEDGE_DB_PASSWORD:-}"
      sslmode: "${PGEDGE_DB_SSLMODE:-prefer}"
      allow_writes: false
YAML_DB
    fi

    # Then add numbered databases (1-99)
    for n in $(seq 1 99); do
        eval "db_name=\$PGEDGE_DB_${n}_NAME"
        eval "db_host=\$PGEDGE_DB_${n}_HOST"
        eval "db_port=\$PGEDGE_DB_${n}_PORT"
        eval "db_database=\$PGEDGE_DB_${n}_DATABASE"
        eval "db_user=\$PGEDGE_DB_${n}_USER"
        eval "db_password=\$PGEDGE_DB_${n}_PASSWORD"
        eval "db_sslmode=\$PGEDGE_DB_${n}_SSLMODE"
        eval "db_allow_writes=\$PGEDGE_DB_${n}_ALLOW_WRITES"

        # Skip if this numbered database is not configured
        if [ -z "$db_name" ] && [ -z "$db_host" ]; then
            continue
        fi

        DB_COUNT=$((DB_COUNT + 1))

        # Set defaults
        db_name="${db_name:-db${n}}"
        db_host="${db_host:-localhost}"
        db_port="${db_port:-5432}"
        db_database="${db_database:-${db_name}}"
        db_user="${db_user:-postgres}"
        db_password="${db_password:-}"
        db_sslmode="${db_sslmode:-prefer}"

        # Convert allow_writes to boolean
        case "$db_allow_writes" in
            true|TRUE|1|yes|YES) db_allow_writes="true" ;;
            *) db_allow_writes="false" ;;
        esac

        cat >> "$config_file" << YAML_DB
    - name: "${db_name}"
      host: "${db_host}"
      port: ${db_port}
      database: "${db_database}"
      user: "${db_user}"
      password: "${db_password}"
      sslmode: "${db_sslmode}"
      allow_writes: ${db_allow_writes}
YAML_DB
    done

    chown 1001:1001 "$config_file"
    echo "Generated config with $DB_COUNT database(s)"
}

# Check if multiple databases are configured
if has_multiple_databases; then
    echo "Multiple databases detected, will generate config file..."
    USE_CONFIG_FILE=true
else
    USE_CONFIG_FILE=false
    # Add single database connection via command line args (backward compatible)
    if [ -n "$PGEDGE_DB_HOST" ]; then
        ARGS="$ARGS -db-host $PGEDGE_DB_HOST"
    fi

    if [ -n "$PGEDGE_DB_PORT" ]; then
        ARGS="$ARGS -db-port $PGEDGE_DB_PORT"
    fi

    if [ -n "$PGEDGE_DB_NAME" ]; then
        ARGS="$ARGS -db-name $PGEDGE_DB_NAME"
    fi

    if [ -n "$PGEDGE_DB_USER" ]; then
        ARGS="$ARGS -db-user $PGEDGE_DB_USER"
    fi

    if [ -n "$PGEDGE_DB_PASSWORD" ]; then
        ARGS="$ARGS -db-password $PGEDGE_DB_PASSWORD"
    fi

    if [ -n "$PGEDGE_DB_SSLMODE" ]; then
        ARGS="$ARGS -db-sslmode $PGEDGE_DB_SSLMODE"
    fi
fi

# Add token file path if provided
if [ -n "$PGEDGE_TOKEN_FILE" ]; then
    ARGS="$ARGS -token-file $PGEDGE_TOKEN_FILE"
else
    # Default token file location
    ARGS="$ARGS -token-file /app/data/tokens.json"
fi

# Add user file path if provided
if [ -n "$PGEDGE_USERS_FILE" ]; then
    ARGS="$ARGS -user-file $PGEDGE_USERS_FILE"
else
    # Default user file location
    ARGS="$ARGS -user-file /app/data/users.json"
fi

# Add debug flag if requested
if [ "$PGEDGE_DEBUG" = "true" ]; then
    ARGS="$ARGS -debug"
fi

# Check for built-in knowledgebase database
# If the KB exists in the image and PGEDGE_KB_DATABASE_PATH is not already set,
# automatically configure the KB path
KB_BUILTIN_PATH="/usr/share/pgedge/nla-kb/kb.db"
if [ -f "$KB_BUILTIN_PATH" ]; then
    echo "Built-in knowledgebase database found at $KB_BUILTIN_PATH"
    if [ -z "$PGEDGE_KB_DATABASE_PATH" ]; then
        export PGEDGE_KB_DATABASE_PATH="$KB_BUILTIN_PATH"
        echo "Set PGEDGE_KB_DATABASE_PATH=$KB_BUILTIN_PATH"
    else
        echo "Using configured PGEDGE_KB_DATABASE_PATH=$PGEDGE_KB_DATABASE_PATH"
    fi
fi

# Create data directory with proper permissions
# This directory stores:
# - Authentication tokens (tokens.json)
# - User credentials (users.json)
# - Conversation history (conversations.db)
# - User preferences
# - Generated config files (postgres-mcp.yaml)
DATA_DIR="${PGEDGE_DATA_DIR:-/app/data}"
echo "Data directory: $DATA_DIR"
mkdir -p "$DATA_DIR"
chown 1001:1001 "$DATA_DIR"

# Ensure PGEDGE_DATA_DIR is exported for the server process
export PGEDGE_DATA_DIR="$DATA_DIR"

# Generate config file if multiple databases are configured
if [ "$USE_CONFIG_FILE" = "true" ]; then
    CONFIG_FILE="${DATA_DIR}/postgres-mcp.yaml"
    generate_multi_db_config "$CONFIG_FILE"
    ARGS="$ARGS -config $CONFIG_FILE"
    echo "Config file generated at: $CONFIG_FILE"
    # Show config with passwords masked for security
    echo "Config file contents (passwords masked):"
    sed 's/password: ".*"/password: "***"/' "$CONFIG_FILE"
fi

# Initialize token file if INIT_TOKENS is provided
TOKEN_FILE="${PGEDGE_TOKEN_FILE:-${DATA_DIR}/tokens.json}"
if [ -n "$INIT_TOKENS" ]; then
    echo "Initializing tokens from INIT_TOKENS environment variable..."

    # Create tokens.json from INIT_TOKENS (expected format: token1,token2,token3)
    # Structure must match TokenStore struct: {"tokens": {"token-id": {...}}}
    echo "{" > "$TOKEN_FILE"
    echo "  \"tokens\": {" >> "$TOKEN_FILE"
    FIRST=true
    IFS=','
    for token in $INIT_TOKENS; do
        if [ "$FIRST" = true ]; then
            FIRST=false
        else
            echo "," >> "$TOKEN_FILE"
        fi
        # Hash the token using SHA256 (same as internal/auth/auth.go:HashToken)
        token_hash=$(echo -n "$token" | sha256sum | cut -d' ' -f1)
        echo "    \"$token\": {" >> "$TOKEN_FILE"
        echo "      \"hash\": \"$token_hash\"," >> "$TOKEN_FILE"
        echo "      \"created_at\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"," >> "$TOKEN_FILE"
        echo "      \"annotation\": \"Auto-generated token\"" >> "$TOKEN_FILE"
        echo -n "    }" >> "$TOKEN_FILE"
    done
    echo "" >> "$TOKEN_FILE"
    echo "  }" >> "$TOKEN_FILE"
    echo "}" >> "$TOKEN_FILE"
    chown 1001:1001 "$TOKEN_FILE"

    echo "Created token file with $(echo "$INIT_TOKENS" | tr ',' '\n' | wc -l | tr -d ' ') tokens"
    echo "Token file initialized"
else
    # Create empty tokens.json (no tokens initialized)
    # Structure must match TokenStore struct: {"tokens": {}}
    echo "{\"tokens\": {}}" > "$TOKEN_FILE"
    chown 1001:1001 "$TOKEN_FILE"
    echo "Created empty token file (no tokens initialized)"
fi

# Initialize users file if INIT_USERS is provided
USERS_FILE="${PGEDGE_USERS_FILE:-${DATA_DIR}/users.json}"
if [ -n "$INIT_USERS" ]; then
    echo "Initializing users from INIT_USERS environment variable..."

    # Create empty users file first
    echo "{}" > "$USERS_FILE"
    chown 1001:1001 "$USERS_FILE"

    # Use the server's -add-user command to properly hash passwords
    # Expected format: username1:password1,username2:password2
    IFS=','
    USER_COUNT=0
    for user_entry in $INIT_USERS; do
        username=$(echo "$user_entry" | cut -d: -f1)
        password=$(echo "$user_entry" | cut -d: -f2-)

        # Add user using the server's built-in command (which hashes the password)
        /app/pgedge-postgres-mcp -add-user -username "$username" -password "$password" -user-file "$USERS_FILE" -user-note "Auto-generated user"
        USER_COUNT=$((USER_COUNT + 1))
    done

    echo "Created users file with $USER_COUNT user(s)"
fi

# Ensure all data files are owned by user 1001
if [ -f "$TOKEN_FILE" ]; then
    chown 1001:1001 "$TOKEN_FILE"
fi
if [ -f "$USERS_FILE" ]; then
    chown 1001:1001 "$USERS_FILE"
fi

# Start the MCP server with all arguments
echo "Starting MCP server"

# Switch to mcp user and exec the server (use runuser which is available in ubi9-minimal)
exec runuser mcp /bin/sh -c "exec /app/pgedge-postgres-mcp $ARGS"
