name: CI - Documentation

on:
    push:
        branches: [ main, develop, 'feat/llm-lib-*' ]
    pull_request:
        branches: [ main, develop, 'feat/llm-lib-*' ]
    workflow_dispatch:

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    docs:
        name: Documentation
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

            - name: Set up Python
              uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
              with:
                  python-version: '3.14'
                  cache: 'pip'

            - name: Create virtual environment
              run: |
                  python3 -m venv venv
                  source venv/bin/activate
                  pip install -r requirements.txt

            - name: Build documentation
              run: |
                  source venv/bin/activate
                  mkdocs build -v

            - name: Upload documentation artifact
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
              with:
                  if-no-files-found: error
                  name: pgedge-docs-site
                  path: site
                  retention-days: 7
